### ISSUE TITLE
코딩하기 좋은 카페의 필수조건을 항목화 해보면 어떨까요?

### ISSUE THREAD

**Issue by devtedlee** [OpenMogaco/awesome-coding-places#2]
제가 생각하는 조건 예시

1. 와이파이 속도
2. 콘센트 갯수
3. 좌석이 충분히 편안한지(오래 앉아있지 못하게 만든 좌석들이 있어서요)

**Comment by rkttu** [comment]
좋은 제안입니다. 다만 고민이 좀 있습니다. 필수 조건을 넣기 시작하면 카페 항목들마다 차등이 발생할 수 있어서 데이터베이스의 완성도가 낮아질 수 있고 제안을 추가하기 어려워지는 점이 있어서 "추천 지수"라는 것을 들여왔는데 추천지수의 기준으로 제안해주신 항목들을 반영하는 것이 어떨까 하는 고민이 있습니다.

**Comment by cometkim** [comment]
아주 좋은 저장소네요 ✨ 

새벽 코딩을 주로 해서 개인적으로 24시간 영업 여부도 꽤 중요한데 이런 바이너리식 항목들은 무난하게 들어갈 수 있지 않을까요

**Comment by rkttu** [comment]
@cometkim 그러게요. 좋은 아이디어입니다. 👍

**Comment by devtedlee** [comment]
그럼 일단 데이터 모이는거 지켜보다가 정리해도 좋을거 같네요~
